version: '3.8'

services:
  llm_service:
    build: ./llm_service
    ports:
      - "${LLM_SERVICE_PORT}:5000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_QUEUE_PORT}
    volumes:
      - ./llm_service:/app

networks:
  default:
    name: shared_rabbitmq_network
    external: true